export const UPDATE_ON_LINE_USERS = 'UPDATE_ON_LINE_USERS';
export const UPDATE_AJAX_ANIMATION = 'UPDATE_AJAX_ANIMATION';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const GET_CHARACTER_COUNT_SUCCESS = 'GET_CHARACTER_COUNT_SUCCESS';
export const GET_CHARACTER_COUNT_FAIL = 'GET_CHARACTER_COUNT_FAIL';
export const FIND_CHARACTER_SUCCESS = 'FIND_CHARACTER_SUCCESS';
export const FIND_CHARACTER_FAIL = 'FIND_CHARACTER_FAIL';